version: '3'
services:
  subscriber:
    image: xjasonlyu/subscriber:latest
    volumes:
      - /etc/subscriber:/config:ro
      # - $PWD/subscribe:/subscribe:ro
    restart: always
    network_mode: host
    # command: --debug
    container_name: subscriber
