version: '3'
services:
  subscriber:
    image: xjasonlyu/subscriber:latest
    volumes:
      - $PWD/config:/config:ro
      # - $PWD/subscribe:/subscribe:ro
      # - $PWD/main.py:/main.py:ro
    restart: always
    network_mode: host
    # command: --debug
    container_name: subscriber
